/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LocadoraBrasileiradeCarros;

/*Uma locadora brasileira de carros cobra um valor por hora para locações 
de até 12 horas. Porém, se a duração da locação ultrapassar 12 horas, a 
locação será cobrada com base em um valor diário. 
Além do valor dalocação, é acrescido no preço o valor do imposto conforme
as regras do país que, no caso do Brasil, é de 2% para valores até 
R$ 100, ou 15% para os valores acima de R$ 100.
Fazer um programa que lê os dados da locação (modelo do carro, instante 
inicial e final da locação), bem como o valor por hora e o valor diário 
da locação. 
O programa deve então gerar a nota de pagamento (contendo valor da 
locação, valor do imposto e valor total do pagamento) e informar os dados na 
tela. 
*/

public class App {
    
}
